import {
  Github,
  Linkedin,
  Instagram,
  Twitter,
  YoutubeIcon,
  Globe,
  Facebook,
} from 'lucide-react';

export const PLATFORMS = [
  {
    id: 1,
    value: 'github',
    label: 'Github',
    icon: Github,
    color: 'bg-[#24292E]',
    link: '',
  },
  {
    id: 2,
    value: 'linkedin',
    label: 'Linkedin',
    icon: Linkedin,
    color: 'bg-[#0072B1]',
    link: '',
  },
  {
    id: 3,
    value: 'twitter',
    label: 'Twitter',
    icon: Twitter,
    color: 'bg-[#1DA1F2]',
    link: '',
  },
  {
    id: 4,
    value: 'instagram',
    label: 'Instagram',
    icon: Instagram,
    color: 'bg-[#F2A60C]',
    link: '',
  },
  {
    id: 5,
    value: 'youtube',
    label: 'Youtube',
    icon: YoutubeIcon,
    color: 'bg-[#C4302B]',
    link: '',
  },
  {
    id: 6,
    value: 'facebook',
    label: 'Facebook',
    icon: Facebook,
    color: 'bg-[#1877F2]',
    link: '',
  },
  {
    id: 7,
    value: 'website',
    label: 'Website',
    icon: Globe,
    color: 'bg-[#15803D]',
    link: '',
  },
];
